name: Validate Branch Name

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate branch name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Validating branch name: $BRANCH_NAME"

          # Add your regex here, same you use in validate-branch-name package
          REGEX="^(main){1}$|^(chore|hotfix)\\/([\\/\\w\\-\\d]+)$|^(\\w+-\\d+)\\/([\\w\\-\\d]+)$|^(dependabot\\/npm_and_yarn-[\\w\\-\\d\\.]+)$"
          if ! [[ "$BRANCH_NAME" =~ $REGEX ]]; then
            echo "::error title=Invalid branch name::Branch name '$BRANCH_NAME' does not match the required pattern."
            exit 1
          fi
