name: Deploy
on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    paths:
      - prisma/migrations/** # Only run this workflow when migrations are updated
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.16
      - name: Install dependencies
        run: npm install
      - name: Print DATABASE_URL for debugging
        run: "echo 'DATABASE_URL is set: ${{ secrets.DATABASE_URL != '' }}'"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Test database connection
        run: npx prisma db push --skip-generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
