name: Migrate Prisma Database
on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    paths:
      - prisma/migrations/** # Only run this workflow when migrations are updated
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.16
      - name: Install dependencies
        run: npm install
      - name: Apply all pending migrations to the database
        env:
          DATABASE_URL: ${{ secrets.DIRECT_URL }}
          # DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: npx prisma migrate deploy
